import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[window]
option_as_alt = "OnlyLeft"
decorations = "Full"
opacity = 1.0
blur = false

[env]
TERM = "xterm-256color"


[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
