require 'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "typescript",
    "javascript",
    "go",
    "elixir",
    "lua",
    "html",
    "vim",
    "http",
    "jq",
    "jsdoc",
    "make",
    "markdown",
    "markdown_inline",
    "prisma",
    "python",
    "regex",
    "ruby",
    "rust",
    "css",
    "sql",
    "terraform",
    "toml",
    "tsx",
    "yaml",
    "diff",
    "git_rebase",
    "gitattributes",
    "gitignore",
    "json",
    "help"
  },
  sync_install = true,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false
  }
}
